server:
  port: 8093

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rsweethut/config-server
          clone-on-start: true